# Generated by Django 3.0.10 on 2020-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hours', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('start', models.DateField()),
            ],
        ),
    ]
