# Generated by Django 3.0.10 on 2020-10-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('starts', models.DateField()),
                ('finishes', models.DateField()),
                ('max_student_counts', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Technology')),
            ],
        ),
    ]
