# Generated by Django 3.0.10 on 2020-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='max_student_counts',
            new_name='max_atendees_counts',
        ),
        migrations.AddField(
            model_name='course',
            name='remote',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
