# Generated by Django 3.0.10 on 2020-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
