# Generated by Django 3.1.3 on 2021-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
